# Generated by Django 5.2 on 2025-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Economie', 'Economie'), ('Droit', 'Droit'), ('Langue Etrangere applique', 'Langue Etrangere Applique'), ('Education', 'Education'), ('Communication', 'Communication'), ('Agronomie', 'Agronomie')], max_length=100)),
                ('niveau', models.CharField(choices=[('L2', 'L2'), ('L3', 'L3')], max_length=10)),
                ('interets', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('avis_responsable', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
